blank_issues_enabled: false
contact_links:
  - name: Don't have GitHub? (link not ready)
    url: https://github.com/adamraichu
    about: If you don't have GitHub, you can report problems and give suggestions here.