name: Validate maps.js
on: 
  workflow_dispatch:
  push:
jobs:
  npm:
    name: Use node to run validation.js.
    runs-on: ubuntu-latest
    steps:
    - name: import GitHub actions checkout
      uses: actions/checkout@v3
    - name: import Node
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: run validation.js
      uses: actions/github-script@v6
      with:
        script: |
          var validate = require("./validation.js");
          validate();